# Android language used because it installs Android SDK required by DroidMate.
language: android

addons:
  apt:
    packages:
      # Required by org.droidmate.report.plot()
      - gnuplot

git:
  # To speed up things. By default it is 50.
  depth: 1

jdk:

  # Most of DroidMate is compiled with Java 8.
  - oraclejdk8

android:
  components:

    # Build tools
    # Tools package is required by Travis-CI in order to locate "build-tools",
    # Official bugtracker issue: https://github.com/travis-ci/travis-ci/issues/5036
    # More info: https://docs.travis-ci.com/user/languages/android/#Overview
    - tools
    - platform-tools
    - build-tools-26.0.2
    # Packages required by UIAutomator2
    - extra-android-support
    - extra-android-m2repository

    # DroidMate supports Android API 23 (6.0.1).
    - android-23
    # - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-google_apis-23
    - sys-img-armeabi-v7a-addon-google_apis-google-23
    # - sys-img-x86_64-google_apis-23
    # - sys-img-x86_64-addon-google_apis-google-23
    - android-25
    - android-26

env:
  global:

    # Required to obtain reference to jarsigner.
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

    # Required to obtain handles to aapt and adb.
    - ANDROID_HOME=/usr/local/android-sdk

before_install:

  # Change to the directory containing the main build script of DroidMate.
  # - cd dev/droidmate

  # Allow Gradle build script to execute.
  - chmod +x gradlew
  # By default, 'android' language uses 'connectedCheck'. Here we replace it with appropriate task.
  - ./gradlew build install
  - ./gradlew shadowJar
  - cp ./project/pcComponents/API/build/libs/*.jar .

  # copy the apk
  - wget -qq -O ./apks/TippyTipper-debug.apk  https://software.imdea.org/cloud/index.php/s/z7K9ZCrjSo05Jbi/download

before_cache:

  # Allow Gradle to use cache.
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:

    # Cache gradle dirs.
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Note: Android SDK should not be cached, according to https://docs.travis-ci.com/user/caching/#Things-not-to-cache


before_script:
    - echo no | android create avd --force -n droidmate_nexus72013_23_GAPPS_ARM -t android-23 --abi "google_apis/armeabi-v7a" -d "Nexus 7 2013" --skin "WSVGA"
    - emulator -verbose -debug-all -avd droidmate_nexus72013_23_GAPPS_ARM -no-boot-anim -no-audio -no-window &> emu_droidmate_nexus72013_23_GAPPS_ARM.log &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    # Run droidmate 300 secs
    - java -jar shadow-1.0-RC1-all.jar --Selectors-timeLimit=300 &> tool_run.log

after_script:
    # - cat emu_droidmate_nexus72013_23_GAPPS_ARM.log
    - cat tool_run.log
